# Generated by Django 3.2.16 on 2023-12-05 23:41

import colorfield.fields
from django.db import migrations
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20231205_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None, unique=True, validators=[recipes.validators.validate_hex_color], verbose_name='Цветовой код'),
        ),
    ]
