# Generated by Django 3.2.16 on 2023-12-06 13:09

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231205_2207'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='author_is_not_user',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('following', django.db.models.expressions.F('user')), _negated=True), name='user_is_not_following'),
        ),
    ]
